import { existsSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const apiDocsDirectoryPath = resolve(
    fileURLToPath(new URL("./site-docs/developer/api", import.meta.url))
);

const hasGeneratedApiDocs = (() => {
    if (!existsSync(apiDocsDirectoryPath)) {
        return false;
    }

    return readdirSync(apiDocsDirectoryPath, {
        recursive: true,
    }).some((entryName) => /\.(?:md|mdx)$/u.test(String(entryName)));
})();

const generatedApiSidebarCategory = {
    collapsed: false,
    items: [
        {
            dirName: "developer/api",
            type: "autogenerated" as const,
        },
    ],
    label: "📘 API",
    link: {
        description:
            "Generated API documentation for the plugin runtime and internal helpers.",
        title: "API",
        type: "generated-index" as const,
    },
    type: "category" as const,
};

/** Main sidebar configuration for the primary documentation section. */
const sidebars = {
    docs: [
        {
            id: "developer/index",
            label: "Developer Docs",
            type: "doc",
        },
        {
            id: "developer/docusaurus-site-contract",
            label: "🧭 Docs Site Contract",
            type: "doc",
        },
        ...(hasGeneratedApiDocs ? [generatedApiSidebarCategory] : []),
    ],
} satisfies SidebarsConfig;

export default sidebars;
