import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const packageName = "stylelint-plugin-container-query-sanity";

const sidebars: SidebarsConfig = {
    docs: [
        {
            className: "sb-cat-developer",
            id: "developer/index",
            label: "🛠️ Developer Guide",
            type: "doc",
        },
        {
            className: "sb-cat-developer-ops",
            id: "developer/docusaurus-site-contract",
            label: "📜 Docs Site Contract",
            type: "doc",
        },
        {
            className: "sb-cat-api-overview",
            collapsed: true,
            collapsible: true,
            customProps: {
                badge: "api-overview",
            },
            items: [
                {
                    className: "sb-api-overview-item",
                    id: "developer/api/plugin/index",
                    label: "Plugin API index",
                    type: "doc",
                },
                {
                    className: "sb-api-overview-item",
                    id: "developer/api/plugin/variables/containerQuerySanityPluginConfigs",
                    label: "Shareable config exports",
                    type: "doc",
                },
                {
                    className: "sb-api-overview-item",
                    id: "developer/api/plugin/variables/rules",
                    label: "Rule registry exports",
                    type: "doc",
                },
            ],
            label: "📘 API Overview",
            link: {
                id: "developer/api/index",
                type: "doc",
            },
            type: "category",
        },
        {
            className: "sb-cat-api-types",
            collapsed: true,
            collapsible: true,
            customProps: {
                badge: "types",
            },
            items: [
                {
                    dirName: "developer/api/plugin/type-aliases",
                    type: "autogenerated",
                },
                {
                    dirName:
                        "developer/api/internal/container-query-analysis/type-aliases",
                    type: "autogenerated",
                },
            ],
            label: "🏷️ Types",
            link: {
                description:
                    "Type-level contracts for the public plugin API and query analysis helpers.",
                slug: "/category/types",
                title: "Types",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-api-runtime",
            collapsed: true,
            collapsible: true,
            customProps: {
                badge: "runtime",
            },
            items: [
                {
                    collapsed: true,
                    collapsible: true,
                    items: [
                        {
                            dirName: "developer/api/plugin/variables",
                            type: "autogenerated",
                        },
                    ],
                    label: "Plugin variables",
                    type: "category",
                },
                {
                    collapsed: true,
                    collapsible: true,
                    items: [
                        {
                            dirName: "developer/api/internal",
                            type: "autogenerated",
                        },
                    ],
                    label: "Internal API",
                    type: "category",
                },
            ],
            label: "⚙️ Runtime",
            link: {
                description: `Runtime exports and internal utility references from ${packageName}.`,
                slug: "/category/runtime",
                title: "Runtime Exports",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-dev-links",
            collapsed: true,
            collapsible: true,
            customProps: {
                badge: "links",
            },
            items: [
                {
                    href: "https://nick2bad4u.github.io/stylelint-plugin-container-query-sanity/stylelint-inspector/",
                    label: "🔎 Stylelint Inspector",
                    type: "link",
                },
                {
                    href: "https://nick2bad4u.github.io/stylelint-plugin-container-query-sanity/eslint-inspector/",
                    label: "🧪 ESLint Inspector",
                    type: "link",
                },
                {
                    href: "https://stylelint.io/developer-guide/plugins/",
                    label: "📚 Stylelint Plugin Guide",
                    type: "link",
                },
                {
                    href: `https://github.com/Nick2bad4u/${packageName}/issues?q=is%3Aissue%20is%3Aopen`,
                    label: "🐞 Open issues",
                    type: "link",
                },
                {
                    href: `https://www.npmjs.com/package/${packageName}`,
                    label: "📦 NPM package",
                    type: "link",
                },
            ],
            label: "🔗 Links",
            type: "category",
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
