# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: "Gitleaks Secret Scan"

run-name: >-
  ${{
      github.event_name == 'pull_request' &&
      format('Gitleaks Secret Scan #{0}', github.event.pull_request.number) ||
      github.event_name == 'merge_group' &&
      format('Gitleaks Secret Scan merge group {0}', github.sha || github.ref_name || github.run_id) ||
      github.event_name == 'schedule' &&
      format('Gitleaks Secret Scan scheduled {0}', github.run_id) ||
      format('Gitleaks Secret Scan {0}', github.ref_name || github.run_id)
  }}

concurrency:
  group: >-
    gitleaks-secret-scan-${{ github.workflow }}-${{
        github.event.pull_request.number ||
        github.sha ||
        github.ref ||
        github.run_id
    }}
  cancel-in-progress: true

on:
  pull_request:
  merge_group:
    types:
      - "checks_requested"
  push:
  schedule:
    - cron: "12 4 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  gitleaks:
    name: "Gitleaks Secret Scan"
    permissions:
      contents: "read"
    uses: "Nick2bad4u/workflow-templates/.github/workflows/reusable-gitleaks-scan-enhanced.yml@main"
